/**
 * Shared helper for image-generation plugins: write generated bytes to a
 * file and return its path, instead of returning raw base64.
 *
 * Base64 image payloads in an action result bloat the agent context and are
 * stripped by many hosts before reaching the model, so the agent can never
 * actually deliver the image. A file `path` hands straight to a host
 * send_file/attachment tool. Plugins load in-process via jiti, so node:fs is
 * available (same pattern as googleDrive/googleSlides).
 */
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const MIME_EXT: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/jpg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/svg+xml": "svg",
};

export function extForMime(mimeType: string | undefined): string {
  if (!mimeType) return "png";
  return MIME_EXT[mimeType] ?? mimeType.split("/")[1]?.split("+")[0] ?? "png";
}

export interface SavedImage {
  path: string;
  mimeType: string;
  byteLength: number;
}

/**
 * Decode base64 image bytes and write them to `saveDir` (or the OS temp dir),
 * named `<provider>-<stamp>-<index>.<ext>`. Returns the file path + size.
 */
export function writeImageFile(opts: {
  base64: string;
  mimeType?: string;
  provider: string;
  index: number;
  saveDir?: string;
  stamp?: number;
}): SavedImage {
  const mimeType = opts.mimeType ?? "image/png";
  const dir = (typeof opts.saveDir === "string" && opts.saveDir.trim()) || tmpdir();
  const bytes = Buffer.from(opts.base64 ?? "", "base64");
  const stamp = opts.stamp ?? Date.now();
  const path = join(dir, `${opts.provider}-${stamp}-${opts.index}.${extForMime(mimeType)}`);
  writeFileSync(path, bytes);
  return { path, mimeType, byteLength: bytes.length };
}

export const SEND_FILE_NOTE =
  "Image(s) written to disk. Deliver each to the user with send_file using its `path`.";
