/**
 * Shared helper for media-generating plugins: write generated bytes to a
 * file and return its path, instead of returning raw base64.
 *
 * Base64 payloads in an action result bloat the agent context and are
 * stripped by many hosts before reaching the model, so the agent can never
 * actually deliver the file. A file `path` hands straight to a host
 * send_file/attachment tool. Plugins load in-process via jiti, so node:fs is
 * available (same pattern as googleDrive/googleSlides).
 */
import { randomUUID } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, extname, join } from "node:path";

const MIME_EXT: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/jpg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "video/quicktime": "mov",
  "audio/mpeg": "mp3",
  "audio/mp3": "mp3",
  "audio/wav": "wav",
  "audio/x-wav": "wav",
  "audio/ogg": "ogg",
};

export function extForMime(mimeType: string | undefined): string {
  if (!mimeType) return "png";
  const mime = mimeType.split(";")[0].trim().toLowerCase();
  return Object.hasOwn(MIME_EXT, mime) ? MIME_EXT[mime] : "bin";
}

export interface SavedMedia {
  path: string;
  mimeType: string;
  byteLength: number;
}

/**
 * Write media bytes with a unique name in `saveDir` (or the OS temp dir).
 * Exclusive creation prevents overwrites and following a pre-existing file symlink.
 */
export function writeMediaFile(opts: {
  bytes: Uint8Array;
  mimeType?: string;
  provider: string;
  index: number;
  saveDir?: string;
  stamp?: number;
}): SavedMedia {
  const mimeType = opts.mimeType ?? "image/png";
  const dir = (typeof opts.saveDir === "string" && opts.saveDir.trim()) || tmpdir();
  const stamp = opts.stamp ?? Date.now();
  if (!/^[\w-]+$/.test(opts.provider)) throw new Error("invalid media provider name");
  const path = join(dir, `${opts.provider}-${stamp}-${opts.index}-${randomUUID()}.${extForMime(mimeType)}`);
  writeFileSync(path, opts.bytes, { flag: "wx", mode: 0o600 });
  return { path, mimeType, byteLength: opts.bytes.byteLength };
}

/**
 * Decode base64 media bytes and write them, for the providers that answer
 * with base64 rather than a URL to download.
 */
export function writeImageFile(opts: {
  base64: string;
  mimeType?: string;
  provider: string;
  index: number;
  saveDir?: string;
  stamp?: number;
}): SavedMedia {
  const { base64, ...rest } = opts;
  return writeMediaFile({ ...rest, bytes: Buffer.from(base64 ?? "", "base64") });
}

export const SEND_FILE_NOTE =
  "File(s) written to disk. Deliver each to the user with send_file using its `path`.";

const EXT_MIME: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
};

export interface LoadedImage {
  bytes: Buffer;
  base64: string;
  mimeType: string;
  dataUri: string;
  fileName: string;
}

/**
 * Read a local image for an `image.edit` call: bytes + base64 + mime
 * (from the extension) + a `data:` URI for JSON APIs. Throws with the
 * plugin's name when the file can't be read so errors point at the
 * right tool.
 */
export function readImageInput(imagePath: string, pluginName: string): LoadedImage {
  if (typeof imagePath !== "string" || imagePath.trim().length === 0) {
    throw new Error(`${pluginName}: imagePath is required`);
  }
  let bytes: Buffer;
  try {
    bytes = readFileSync(imagePath);
  } catch (err) {
    throw new Error(
      `${pluginName}: cannot read image at ${imagePath} — ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  const ext = extname(imagePath).slice(1).toLowerCase();
  const mimeType = EXT_MIME[ext] ?? "image/png";
  const base64 = bytes.toString("base64");
  return {
    bytes,
    base64,
    mimeType,
    dataUri: `data:${mimeType};base64,${base64}`,
    fileName: basename(imagePath),
  };
}
